const UPDATE_POST = 'UPDATE_POST';

const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
const SUCCESS_CREATE_POST = 'SUCCESS_CREATE_POST';
const ERROR_CREATE_POST = 'ERROR_CREATE_POST';

const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
const RECEIVE_POST_BY_ID = 'RECEIVE_POST_BY_ID';
const ERROR_ON_FETCH_POST_BY_ID = 'ERROR_ON_FETCH_POST_BY_ID';

const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
const SUCCESS_EDIT_POST = 'SUCCESS_EDIT_POST';
const ERROR_EDIT_POST = 'ERROR_EDIT_POST';

const DELETE_POST_BY_ID = 'DELETE_POST_BY_ID';
const SUCCESS_DELETE_POST_BY_ID = 'SUCCESS_DELETE_POST_BY_ID';
const ERROR_ON_DELETE_POST_BY_ID = 'ERROR_ON_DELETE_POST_BY_ID';

const REQUEST_INCREMENT_VOTE_POST = 'REQUEST_INCREMENT_VOTE_POST';
const REQUEST_DECREMENT_VOTE_POST = 'REQUEST_DECREMENT_VOTE_POST';

export {
  UPDATE_POST,
  CREATE_POST_REQUEST,
  SUCCESS_CREATE_POST,
  ERROR_CREATE_POST,
  FETCH_POST_BY_ID,
  RECEIVE_POST_BY_ID,
  ERROR_ON_FETCH_POST_BY_ID,
  EDIT_POST_REQUEST,
  SUCCESS_EDIT_POST,
  ERROR_EDIT_POST,
  DELETE_POST_BY_ID,
  SUCCESS_DELETE_POST_BY_ID,
  ERROR_ON_DELETE_POST_BY_ID,
  REQUEST_INCREMENT_VOTE_POST,
  REQUEST_DECREMENT_VOTE_POST,
};
