const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
const ERROR_ON_FETCH_CATEGORIES = 'ERROR_ON_FETCH_CATEGORIES';

export { FETCH_CATEGORIES, RECEIVE_CATEGORIES, ERROR_ON_FETCH_CATEGORIES };
