const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
const ERROR_ON_FETCH_CATEGORIES = 'ERROR_ON_FETCH_CATEGORIES';

const FETCH_POSTS = 'FETCH_POSTS';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const ERROR_ON_FETCH_POSTS = 'ERROR_ON_FETCH_POSTS';

const UPDATE_POST_VOTE_COUNT = 'UPDATE_POST_VOTE_COUNT';

export {
  // categories
  FETCH_CATEGORIES,
  RECEIVE_CATEGORIES,
  ERROR_ON_FETCH_CATEGORIES,

  // posts
  FETCH_POSTS,
  RECEIVE_POSTS,
  ERROR_ON_FETCH_POSTS,

  // post
  UPDATE_POST_VOTE_COUNT,

};
