const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
const ERROR_ON_FETCH_CATEGORIES = 'ERROR_ON_FETCH_CATEGORIES';

const FETCH_POSTS = 'FETCH_POSTS';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const ERROR_ON_FETCH_POSTS = 'ERROR_ON_FETCH_POSTS';

const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
const RECEIVE_POST_BY_ID = 'RECEIVE_POST_BY_ID';
const ERROR_ON_FETCH_POST_BY_ID = 'ERROR_ON_FETCH_POST_BY_ID';


const REQUEST_INCREMENT_VOTE_POST = 'REQUEST_INCREMENT_VOTE_POST';
const REQUEST_DECREMENT_VOTE_POST = 'REQUEST_DECREMENT_VOTE_POST';

const UPDATE_POST = 'UPDATE_POST';

export {
  // categories
  FETCH_CATEGORIES,
  RECEIVE_CATEGORIES,
  ERROR_ON_FETCH_CATEGORIES,

  // posts
  FETCH_POSTS,
  RECEIVE_POSTS,
  ERROR_ON_FETCH_POSTS,

  // post
  UPDATE_POST,

  FETCH_POST_BY_ID,
  RECEIVE_POST_BY_ID,
  ERROR_ON_FETCH_POST_BY_ID,

  REQUEST_INCREMENT_VOTE_POST,
  REQUEST_DECREMENT_VOTE_POST,
};
