const FETCH_COMMENTS_BY_POST_ID = 'FETCH_COMMENTS_BY_POST_ID';
const RECEIVE_COMMENTS_BY_POST_ID = 'RECEIVE_COMMENTS_BY_POST_ID';
const ERROR_ON_FETCH_COMMENTS = 'ERROR_ON_FETCH_COMMENTS';

export { FETCH_COMMENTS_BY_POST_ID, RECEIVE_COMMENTS_BY_POST_ID, ERROR_ON_FETCH_COMMENTS };
