const UPDATE_COMMENT = 'UPDATE_COMMENT';

const REQUEST_INCREMENT_VOTE_COMMENT = 'REQUEST_INCREMENT_VOTE_COMMENT';
const REQUEST_DECREMENT_VOTE_COMMENT = 'cREQUEST_DECREMENT_VOTE_COMMENT';

const DELETE_COMMENT_BY_ID = 'DELETE_COMMENT_BY_ID';
const SUCCESS_DELETE_COMMENT_BY_ID = 'SUCCESS_DELETE_COMMENT_BY_ID';
const ERROR_ON_DELETE_COMMENT_BY_ID = 'ERROR_ON_DELETE_COMMENT_BY_ID';

const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
const SUCCESS_CREATE_COMMENT = 'SUCCESS_CREATE_COMMENT';
const ERROR_CREATE_COMMENT = 'ERROR_CREATE_COMMENT';

const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
const SUCCESS_EDIT_COMMENT = 'SUCCESS_EDIT_COMMENT';
const ERROR_EDIT_COMMENT = 'ERROR_EDIT_COMMENT';

export {
  UPDATE_COMMENT,
  REQUEST_INCREMENT_VOTE_COMMENT,
  REQUEST_DECREMENT_VOTE_COMMENT,
  DELETE_COMMENT_BY_ID,
  SUCCESS_DELETE_COMMENT_BY_ID,
  ERROR_ON_DELETE_COMMENT_BY_ID,
  CREATE_COMMENT_REQUEST,
  SUCCESS_CREATE_COMMENT,
  ERROR_CREATE_COMMENT,
  EDIT_COMMENT_REQUEST,
  SUCCESS_EDIT_COMMENT,
  ERROR_EDIT_COMMENT,
};
